# Generated by Django 5.0.3 on 2024-08-02 10:09

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_reviews_object_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Review',
            name='data',
            field=models.JSONField(default=reviews.models.data_default_value, null=True),
        ),
    ]
